"use client";

import { craftingStyles } from "galadrielcss";
import { CraftClassesType } from "galadrielcss/src/types/typeManifest";
import { useState } from "react";
// Importing the CSS file generated by Galadriel.CSS
import "./page.css";

export default function Home() {
    const [isLightOn, setIsLightOn] = useState(false);

    const container = craftingStyles(() => ({
        background: "linear-gradient(to right, #0f0c29, #302b63, #24243e)",
        display: "flex",
        justifyContent: "center",
        alignItems: "start",
        height: "100%",
        width: "100%",
    }));

    const lamp = craftingStyles(() => ({
        backgroundImage:
            "linear-gradient(#ffffffb3, #ffffffb3), linear-gradient(#ffffffb3, #ffffffb3), linear-gradient(#ffffffb3, #ffffffb3)",
        backgroundRepeat: "no-repeat",
        backgroundSize: ".20rem 10rem, .6rem 1rem, .9rem 4rem",
        backgroundPosition: "50% 0, .16rem 10rem, .05rem 11rem",
        border: "none",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
        margin: "0 auto",
        height: "15rem",
        width: "1rem",
        before: {
            background: "#ffffff08",
            boxShadow: "inset 2px -2px 10px #ffffff32",
            borderRadius: "50%",
            content: "' '",
            transform: "translateX(-50%)",
            left: "50%",
            bottom: "-15.2rem",
            position: "absolute",
            aspectRatio: "1/1",
            transition: "all .7s",
            height: "15rem",
        },
        after: {
            content: "' '",
            position: "absolute",
        },
    }));

    const light = craftingStyles(() => {
        let lightStyles: CraftClassesType = {
            opacity: "0",
            position: "relative",
            bottom: "-15.2rem",
            before: {
                background: "#ffffff53",
				filter: "drop-shadow(0px 0px 50px #ffffff80)",
                borderRadius: "50%",
                border: ".2rem solid #ffffff0d",
                boxShadow: "0px 0px 80px #ffffff80",
                content: "' '",
                transform: "translate(-50%, -50%)",
                top: "50%",
                left: "50%",
                position: "absolute",
                aspectRatio: "1/1",
                height: "15rem",
            },
        };

        if (isLightOn) {
            lightStyles = { ...lightStyles, opacity: "1" };
        } else {
            lightStyles = { ...lightStyles, opacity: "0" };
        }

        return lightStyles;
    });

    return (
        <main className={container}>
            <div className={lamp} onClick={() => setIsLightOn((prev) => !prev)}>
                <div className={light} />
            </div>
        </main>
    );
}
